# Audit Checks


If checks fail, audit procedures will not go forward. 


```{r}
date_range <- c("2018-01-01", "2018-12-31")

checklist <- tibble(id = seq(1:3), desc = c("Balanced TB", "Correct accounting period", "Bad test"))
```


```{r}
check1 <- df %>% 
  select(-X1) %>% 
  filter(!is.na(type)) %>% 
  summarise(check1 = sum(debit) - sum(credit))

if(check1$check1 == 0){
  cli::cli_alert_success("check1 is ok")
}else{
  cli::cli_alert_danger("check1 is bad")
}

check2 <- df %>% 
  select(-X1) %>% 
  filter(!is.na(type)) %>% 
  mutate(date_check = ifelse(date >= date_range[1] & date <= date_range[2], 0, 1)) %>% 
  summarise(check2 = sum(date_check))

if(check2$check2 == 0){
  cli::cli_alert_success("check2 is ok")
}else{
  cli::cli_alert_danger("check2 is bad")
}
```


```{r}
tibble(check1, check2, check3 = 1)  %>% 
  gather(checks, result) %>% 
  rownames_to_column("id") %>%  
  mutate(id = as.integer(id)) %>% 
  mutate(desc = c("Balanced TB", "Correct accounting period", "Bad test")) %>% 
  ggplot(aes(1, id, color = result > 0)) +
  geom_point(size = 4, fill = "gray", shape = 21) +
  geom_text(aes(label = desc, hjust = ifelse(result > 0, 1.2, -.1)), show.legend = FALSE) +
  geom_vline(xintercept = 1, lty = 2) +
  scale_y_continuous(breaks = seq(1:3), trans = "reverse") +
  scale_color_manual(name = "Result", label = c("Pass", "Fail"), values = c("steelblue", "red")) +
  labs(x = "", 
       y = "") +
  theme_bw() +
  theme(axis.ticks.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "bottom")
```















