--- 
title: "Audit Data Analytics"
author: "Stewart Li"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Improve audit effectiveness and efficiency via data analytics."
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, 
                      comment = ">")

library(tidyverse)
library(lubridate)
```


```{r include=FALSE}
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'tidyverse'
), 'packages.bib')
```


```{r}
df <- read_csv("https://raw.githubusercontent.com/stewartli/auditworkpaper/master/data/gl.csv")
```


# Overview


For data analytics procedures, I follow the framework of [R4DS]().    
For audit data analytics purpose, I follow the general audit procedures.    


## Import data 


From SQL, csv, excel, pdf, HTML, API. 


## Audit checks 


Check PBC before auditing. 


## Reconcilaition


Send out confirmation letter.


## Report


Audit work paper.   
Audit report.    


