on:
  push:
    branches: [main, master]

name: bookdown

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup R
        uses: r-lib/actions/setup-r@main

      - name: Install pandoc and pandoc citeproc
        run: |
          choco install pandoc
          choco install pandoc-citeproc

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("bookdown")'
          R -e 'renv::restore()'

      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      
      
